### PR TITLE
i finished the project

### PR DESCRIPTION
**Pull request by Anas-jaf**

### CODE REVIEW

**Review by Anas-jaf — COMMENTED** [review]
linters fix #2

**Review by Anas-jaf — COMMENTED** [review]
fix #3

**Review by Anas-jaf — COMMENTED** [review]
fix #4

**Comment by Anas-jaf** [comment]
fixed the linters

**Review by Anas-jaf — COMMENTED** [review]
fix @4

**Comment by Anas-jaf** [comment]
finished the project

**Review by LamiaSristy — COMMENTED** [review]
# Status: Invalid Review Request ✖️ 🔴

Hello Team!! ✋ 

# **You cannot merge the branch without the project being approved by any of the reviewers.**

Unfortunately, I have to mark this review request as invalid. 😢

## The issue:
**According to rules, all your GitHub Actions checks need to be successful, to be a valid CRR.**

**I have to mark this review request as invalid because two of your GitHub Actions Linters checks were not successful. Which are:**
 * `Linters / Webhint`
 * `Linters / Stylelint`

Please fix the linters errors at your project and then ask again for a CRR.

Feel free to reach me on slack @LamiaSristy 🙋

Keep up the spirit always. Happy Coding 💻

**Pull request merged**
